### ISSUE TITLE
Benchtest for new user

### ISSUE THREAD

**Issue by CraigFaunce-NOAA** [MattCallahan-NOAA/obs_coverage_reports#1]
This project is essentially "orphaned".  For contributions from FMA to be meaningful, the existing code must first be replicated and generalized for a novice user.  This issue addresses this, only for the sablefish assessment.

**Comment by MattCallahan-NOAA** [comment]
Hey Craig, good to hear from you. This is the first feedback I have gotten on the future of these reports since we presented in February. What is your vision for these?  Does FMA want to adopt them? Let me know how I can help. 

EDIT: Adding you as a contributor.

**Comment by CraigFaunce-NOAA** [comment]
> Hey Craig, good to hear from you. This is the first feedback I have gotten on the future of these reports since we presented in February. What is your vision for these? Does FMA want to adopt them? Let me know how I can help.
> 
> EDIT: Adding you as a contributor.

Matt, here are notes from the meeting Cindy and I had today.  I do not plan on replacing this project, but desire to contribute to it.  https://docs.google.com/document/d/1k0tIhXXEEgweudxZs3X-MiNbPZrVXXJkCJMfQlnOSrs/edit?usp=sharing

**Comment by CraigFaunce-NOAA** [comment]
I ended up forking this repository.  I will be working solo on this and then when I have something to share I will create a merge request for us to review.  FYI - I am only working with sablefish to start.
